config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :hops

  resources :yeasts

  resources :grains

  resources :brewers

end

app/models/brewer.rb
class Brewer < ActiveRecord::Base
end

app/controllers/brewers_controller.rb
class BrewersController < ApplicationController
  before_action :set_brewer, only: [:show, :edit, :update, :destroy]

  # GET /brewers
  # GET /brewers.json
  def index
    @brewers = Brewer.all
  end

  # GET /brewers/1
  # GET /brewers/1.json
  def show
  end

  # GET /brewers/new
  def new
    @brewer = Brewer.new
  end

  # GET /brewers/1/edit
  def edit
  end

  # POST /brewers
  # POST /brewers.json
  def create
    @brewer = Brewer.new(brewer_params)

    respond_to do |format|
      if @brewer.save
        format.html { redirect_to @brewer, notice: 'Brewer was successfully created.' }
        format.json { render :show, status: :created, location: @brewer }
      else
        format.html { render :new }
        format.json { render json: @brewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brewers/1
  # PATCH/PUT /brewers/1.json
  def update
    respond_to do |format|
      if @brewer.update(brewer_params)
        format.html { redirect_to @brewer, notice: 'Brewer was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewer }
      else
        format.html { render :edit }
        format.json { render json: @brewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brewers/1
  # DELETE /brewers/1.json
  def destroy
    @brewer.destroy
    respond_to do |format|
      format.html { redirect_to brewers_url, notice: 'Brewer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewer
      @brewer = Brewer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewer_params
      params.require(:brewer).permit(:first_name, :last_name)
    end
end

app/helpers/brewers_helper.rb
module BrewersHelper
end

app/views/brewers/_form.html.erb
<%= form_for(@brewer) do |f| %>
  <% if @brewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewer.errors.count, "error") %> prohibited this brewer from being saved:</h2>

      <ul>
      <% @brewer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brewers/edit.html.erb
<h1>Editing Brewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewer %> |
<%= link_to 'Back', brewers_path %>

app/views/brewers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brewers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brewers.each do |brewer| %>
      <tr>
        <td><%= brewer.first_name %></td>
        <td><%= brewer.last_name %></td>
        <td><%= link_to 'Show', brewer %></td>
        <td><%= link_to 'Edit', edit_brewer_path(brewer) %></td>
        <td><%= link_to 'Destroy', brewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brewer', new_brewer_path %>

app/views/brewers/new.html.erb
<h1>New Brewer</h1>

<%= render 'form' %>

<%= link_to 'Back', brewers_path %>

app/views/brewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @brewer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @brewer.last_name %>
</p>

<%= link_to 'Edit', edit_brewer_path(@brewer) %> |
<%= link_to 'Back', brewers_path %>