config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :hops

  resources :yeasts

  resources :grains

  resources :brewers

end

app/models/yeast.rb
class Yeast < ActiveRecord::Base
end

app/controllers/yeasts_controller.rb
class YeastsController < ApplicationController
  before_action :set_yeast, only: [:show, :edit, :update, :destroy]

  # GET /yeasts
  # GET /yeasts.json
  def index
    @yeasts = Yeast.all
  end

  # GET /yeasts/1
  # GET /yeasts/1.json
  def show
  end

  # GET /yeasts/new
  def new
    @yeast = Yeast.new
  end

  # GET /yeasts/1/edit
  def edit
  end

  # POST /yeasts
  # POST /yeasts.json
  def create
    @yeast = Yeast.new(yeast_params)

    respond_to do |format|
      if @yeast.save
        format.html { redirect_to @yeast, notice: 'Yeast was successfully created.' }
        format.json { render :show, status: :created, location: @yeast }
      else
        format.html { render :new }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yeasts/1
  # PATCH/PUT /yeasts/1.json
  def update
    respond_to do |format|
      if @yeast.update(yeast_params)
        format.html { redirect_to @yeast, notice: 'Yeast was successfully updated.' }
        format.json { render :show, status: :ok, location: @yeast }
      else
        format.html { render :edit }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yeasts/1
  # DELETE /yeasts/1.json
  def destroy
    @yeast.destroy
    respond_to do |format|
      format.html { redirect_to yeasts_url, notice: 'Yeast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yeast
      @yeast = Yeast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yeast_params
      params.require(:yeast).permit(:name, :description)
    end
end

app/helpers/yeasts_helper.rb
module YeastsHelper
end

app/views/yeasts/_form.html.erb
<%= form_for(@yeast) do |f| %>
  <% if @yeast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yeast.errors.count, "error") %> prohibited this yeast from being saved:</h2>

      <ul>
      <% @yeast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yeasts/edit.html.erb
<h1>Editing Yeast</h1>

<%= render 'form' %>

<%= link_to 'Show', @yeast %> |
<%= link_to 'Back', yeasts_path %>

app/views/yeasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Yeasts</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yeasts.each do |yeast| %>
      <tr>
        <td><%= yeast.name %></td>
        <td><%= yeast.description %></td>
        <td><%= link_to 'Show', yeast %></td>
        <td><%= link_to 'Edit', edit_yeast_path(yeast) %></td>
        <td><%= link_to 'Destroy', yeast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yeast', new_yeast_path %>

app/views/yeasts/new.html.erb
<h1>New Yeast</h1>

<%= render 'form' %>

<%= link_to 'Back', yeasts_path %>

app/views/yeasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yeast.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @yeast.description %>
</p>

<%= link_to 'Edit', edit_yeast_path(@yeast) %> |
<%= link_to 'Back', yeasts_path %>