config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :hops

  resources :yeasts

  resources :grains

  resources :brewers

end

app/models/grain.rb
class Grain < ActiveRecord::Base
	has_and_belongs_to_many :recipes
end

app/controllers/grains_controller.rb
class GrainsController < ApplicationController
  before_action :set_grain, only: [:show, :edit, :update, :destroy]

  # GET /grains
  # GET /grains.json
  def index
    @grains = Grain.all
  end

  # GET /grains/1
  # GET /grains/1.json
  def show
  end

  # GET /grains/new
  def new
    @grain = Grain.new
  end

  # GET /grains/1/edit
  def edit
  end

  # POST /grains
  # POST /grains.json
  def create
    @grain = Grain.new(grain_params)

    respond_to do |format|
      if @grain.save
        format.html { redirect_to @grain, notice: 'Grain was successfully created.' }
        format.json { render :show, status: :created, location: @grain }
      else
        format.html { render :new }
        format.json { render json: @grain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grains/1
  # PATCH/PUT /grains/1.json
  def update
    respond_to do |format|
      if @grain.update(grain_params)
        format.html { redirect_to @grain, notice: 'Grain was successfully updated.' }
        format.json { render :show, status: :ok, location: @grain }
      else
        format.html { render :edit }
        format.json { render json: @grain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grains/1
  # DELETE /grains/1.json
  def destroy
    @grain.destroy
    respond_to do |format|
      format.html { redirect_to grains_url, notice: 'Grain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grain
      @grain = Grain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grain_params
      params.require(:grain).permit(:name, :description)
    end
end

app/helpers/grains_helper.rb
module GrainsHelper
end

app/views/grains/_form.html.erb
<%= form_for(@grain) do |f| %>
  <% if @grain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grain.errors.count, "error") %> prohibited this grain from being saved:</h2>

      <ul>
      <% @grain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grains/edit.html.erb
<h1>Editing Grain</h1>

<%= render 'form' %>

<%= link_to 'Show', @grain %> |
<%= link_to 'Back', grains_path %>

app/views/grains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grains</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grains.each do |grain| %>
      <tr>
        <td><%= grain.name %></td>
        <td><%= grain.description %></td>
        <td><%= link_to 'Show', grain %></td>
        <td><%= link_to 'Edit', edit_grain_path(grain) %></td>
        <td><%= link_to 'Destroy', grain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grain', new_grain_path %>

app/views/grains/new.html.erb
<h1>New Grain</h1>

<%= render 'form' %>

<%= link_to 'Back', grains_path %>

app/views/grains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @grain.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @grain.description %>
</p>

<%= link_to 'Edit', edit_grain_path(@grain) %> |
<%= link_to 'Back', grains_path %>